In [6]:
#video 6
import numpy
print(numpy.array([1,2]))

[1 2]


In [7]:
print(numpy.array([1,14]))

[ 1 14]


In [9]:
#one dimensional array
import numpy as np
my_list = np.array([1,2,3,4])
print(my_list)

[1 2 3 4]


In [10]:
my_list = [1,2,3,4]
my_array = np.array(my_list)
print(my_array)

[1 2 3 4]


In [13]:
#two dimensional array
import numpy as np
my_list1 = [1,2,3,4]
my_list2 = [5,6,7,8]
my_array = np.array([my_list1, my_list2])
print(my_array)

[[1 2 3 4]
 [5 6 7 8]]


In [25]:
#shape function
import numpy as np
my_list1 = [1,2,3,4]
my_list2 = [5,6,7,8]
my_array = np.array([my_list1, my_list2])
print (my_array.shape)
#2 rows 4 columns

(2, 4)


In [7]:
#to find out the data type
print(my_array.dtype)

int32


In [10]:
#ZEROS
new_array1 = np.zeros(5)
#creates a new numpy array with 1*5, all elements are zero
print(new_array1)

[0. 0. 0. 0. 0.]


In [11]:
new_array1 = np.zeros(7)
print(new_array1)

[0. 0. 0. 0. 0. 0. 0.]


In [12]:
#ones
#usually 2 dimensional
new_array1 = np.ones([5,5])
print(new_array1)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [13]:
new_array1 = np.ones([5,7])
print(new_array1)

[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


In [14]:
new_array = np.empty(5)
print(new_array)

[0. 0. 0. 0. 0.]


In [15]:
new_array = np.eye(5)
print(new_array)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [16]:
new_array = np.arange(5,50,4)
print(new_array)

[ 5  9 13 17 21 25 29 33 37 41 45 49]


In [17]:
#video7
#scaler operations in array
print(5/2)

2.5


In [19]:
array_1 = np.array([(1,2,3,4), (5,6,7,8)])
print(array_1)

[[1 2 3 4]
 [5 6 7 8]]


In [20]:
# multiplication
array2 = array_1 * array_1
print(array2)

[[ 1  4  9 16]
 [25 36 49 64]]


In [22]:
#exponential multiplication
array3 = array_1 **3
print(array3)

[[  1   8  27  64]
 [125 216 343 512]]


In [23]:
#subtraction
print(array3 - array2)

[[  0   4  18  48]
 [100 180 294 448]]


In [24]:
#reciprocal
print(1/array2)

[[1.         0.25       0.11111111 0.0625    ]
 [0.04       0.02777778 0.02040816 0.015625  ]]


In [29]:
#video8
#using index to access elements in an array
#array indexing
arr =np.arange(0,15,2)
print(arr)

[ 0  2  4  6  8 10 12 14]


In [32]:
print(arr[3]) #4th element

6


In [33]:
print(arr[5]) #6th element

10


In [35]:
#slicing
print(arr[0:2])

[0 2]


In [36]:
arr[0:3] =89
print(arr)

[89 89 89  6  8 10 12 14]


In [37]:
#creating array copy
arrcopy = arr.copy()
print (arrcopy)

[89 89 89  6  8 10 12 14]


In [42]:
#video 9
#array index 2 dimensional array
arr2d = ([1,2,3, 4] [5,6,7,8] [9,10,11,12])
print(arr2d[3])

TypeError: list indices must be integers or slices, not tuple

In [3]:
import numpy as np
#video 9
#array index 2 dimensional array
#indexing is picking
arr2d = np.array([(1,2,3, 4), (5,6,7,8), (9,10,11,12)])
print(arr2d[2])

[ 9 10 11 12]


In [4]:
print(arr2d[2][2])

11


In [5]:
print(arr2d)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [7]:
import numpy as np
arr2d = np.array([(1,2,3, 4), (5,6,7,8), (9,10,11,12)])
print(arr2d[0][1])
#0 = first row, 1 = second column in first row

2


In [8]:
print(arr2d[2][3])
# 2= 3rd row, 3= 4th column in 3rd row

12


In [10]:
#slices of 2d array
import numpy as np
arr2d = np.array([(1,2,3, 4), (5,6,7,8), (9,10,11,12)])
slice1 = arr2d[0:1, 0:2]
#that is, row 0, you would not get to 1, column 1, you would not get to 2
print(slice1)

[[1 2]]


In [11]:
import numpy as np
arr2d = np.array([(1,2,3, 4), (5,6,7,8), (9,10,11,12)])
slice1 = arr2d[0:2, 0:2] 
#that is, row 1, you will not get to 2, column 1, you will not get to 1, count from zero
print(slice1)

[[1 2]
 [5 6]]


In [12]:
import numpy as np
arr2d = np.array([(1,2,3, 4), (5,6,7,8), (9,10,11,12)])
slice1 = arr2d[:2, 1:] 
#that is, row 1, you will not get to 2, column 1, till the end, count from zero
print(slice1)

[[2 3 4]
 [6 7 8]]


In [13]:
arr2d[:2, 1:] = 15

In [14]:
print(arr2d)

[[ 1 15 15 15]
 [ 5 15 15 15]
 [ 9 10 11 12]]


In [ ]:
#using loops to index
#10:42
#i don't undewrstand

In [17]:
#video 10
#universal array function
#arrange function
import numpy as np
A = np.arange(15)
print(A)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [18]:
import numpy as np
A = np.arange(1,25,3)
#from 1, tom 25 with a differnce of 3
print(A)

[ 1  4  7 10 13 16 19 22]


In [19]:
#sqrt
#squareroot
b = np.sqrt(A)
print(b)

[1.         2.         2.64575131 3.16227766 3.60555128 4.
 4.35889894 4.69041576]


In [20]:
#exp
#exponential function
c = np.exp(A)
print(c)

[2.71828183e+00 5.45981500e+01 1.09663316e+03 2.20264658e+04
 4.42413392e+05 8.88611052e+06 1.78482301e+08 3.58491285e+09]


In [21]:
#add
#addition
d = np.add(A,b)
print(d)

[ 2.          6.          9.64575131 13.16227766 16.60555128 20.
 23.35889894 26.69041576]


In [23]:
#maximum
e = np.max(A)
print(e)

22


In [24]:
#additional material
#scipy.org
#docs.scipy.org


In [25]:
#video11
#saving and loading numpy array
#saving single arrays
import numpy as np
a = np.arange(25)
np.save('saved array',a)
b = np.load("saved array.npy")
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]


In [ ]:
#how to save multiple array

In [35]:
a = np.arange(25)
b = np.arange(35)
np.savez('saved_c.npz', x = a,y = b)
load_c = np.load("saved_c.npz")
print(load_c['x'])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]


In [37]:
print(load_c['y'])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34]


In [38]:
#how to save to a text file
#3 arguements
#i dont understand again

In [42]:
#video 12
#statistical and mathematical processing of arrays
import numpy as np
import matplotlib.pyplot as plt
axes_values = np.arange(-100,100,10)

In [47]:
import numpy as np
a = np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [50]:
a = np.array([(1,0,0), (0,1,0), (0,0,1)])
print(a)

[[1 0 0]
 [0 1 0]
 [0 0 1]]
